App search result page
pacpacs/pac_application pull request #9
Opened 2019-07-08 02:45 UTC by suhyunNam000

![image](https://user-images.githubusercontent.com/32070288/60779213-cb43b080-a174-11e9-9bb0-7cefe554083f.png)

### 검색 결과 표시 페이지

> selectIngredientPage에서 고른 재료를 Wrap 속의 Chip들로 표시하고, 재료를 기반으로 검색한 결과에 해당하는 레시피를 ListView로 보여준다.

### 추후 진행 사항
> Wrap의 크기가 너무 커지면 사진의 파란색 부분으로 보이는 영역까지가 스크롤 가능 영역이 됨. ListView가 차지하는 부분이 너무 작아지기 때문에 검색 결과를 잘 보이게 하기 위해서 Wrap을 접어서 내용물을 숨길 수 있어야 한다.

2019-07-08 04:09 UTC, SeoYunKyung commented on pac_app/lib/fixed/ingredientChips/ingredientChip.dart
> +//TODO:리스트 아니고 맵이어야함
아예 List 가 아니고 map으로 전체 다 바꿔야한다면 바꿔야하는 코드로 merge해야할 것 같습니다.

2019-07-08 04:09 UTC, SeoYunKyung commented on pac_app/lib/fixed/ingredientChips/ingredientChip.dart
> +  static generateIngredientChip(int categoryCode, String name) {
i like it :smile
categorycode를 나중에 enum으로 관리해주면 좋을 것 같습니다.

2019-07-08 04:11 UTC, SeoYunKyung commented on pac_app/lib/fixed/ingredientChips/ingredientChip.dart
> +            return new Chip(
Chip 이 같은 것이 반복되면 따로 해당 파일 안에 class customChip으로 뺀후 name과 색상만 주는 class로 한후, 같은 기능인 ondeleted를 구현하면 될 것 같습니다. 현재는 계속 코드가 복붙되어있는것 같습니다.

2019-07-08 04:12 UTC, SeoYunKyung commented on pac_app/lib/pages/searchResultPage.dart
> +    return Scaffold(
이 부분은 merge후에 추후 index에 따른 화면 변환시키기 (yanggaeng 제가 하겠습니다) 기억하려고 남겨두는....

2019-07-08 04:12 UTC, SeoYunKyung requested changes
조금 수정되어야하는 부분이 있어보여용 수고하셨습니당 👍

2019-07-21 05:49 UTC, suhyunNam000 commented
1) 재료 삭제 시 칩 업데이트의 용이성을 위해 chip List를 바로 출력하는 방법에서 chip map을 list로 변환하여 출력하는 방법으로 변경했습니다.
2) Custom Chip을 생성하는 메소드를 새로 파서 카테고리 코드에 따라 CircleAvatar 색상이 바뀌도록 만들었습니다.

1)에서 칩의 갯수에 대한 문제가 있는데, bloc을 적용하면 해결된다고 합니다. 추후 bloc적용하도록 하겠습니다.

2019-07-21 06:08 UTC, seoreal commented
같이 수정할 게 많은 것 같아요.. 칩에서 재료랑 공통된 부분을 같이 만들어야할 것 같습니다.

2019-07-21 06:10 UTC, seoreal approved these changes

2019-07-21 07:10 UTC, SeoYunKyung approved these changes
추후 @seoreal 과 협업해서 바꿔주세요

2019-07-21 07:10 UTC, SeoYunKyung commented on pac_app/lib/fixed/ingredientChips/ingredientChip.dart
> +  Color _setHeadColor(int code) {
enum으로 code 처리!

2019-07-21 07:18 UTC, merged